services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syno_movement
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./src:/src
    ports:
      - 9999:9999
    depends_on:
      - codeproject

  codeproject:
    image: codeproject/ai-server
    container_name: CodeProject.AI
    restart: unless-stopped
    ports:
      - 32168:32168